# This rule is not used by the project operator-poc itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over operatorpoc.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-poc
    app.kubernetes.io/managed-by: kustomize
  name: podsvc-admin-role
rules:
- apiGroups:
  - operatorpoc.my.domain
  resources:
  - podsvcs
  verbs:
  - '*'
- apiGroups:
  - operatorpoc.my.domain
  resources:
  - podsvcs/status
  verbs:
  - get
