---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: podsvcs.operatorpoc.my.domain
spec:
  group: operatorpoc.my.domain
  names:
    kind: PodSvc
    listKind: PodSvcList
    plural: podsvcs
    singular: podsvc
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.labelName
      name: Label
      type: string
    - jsonPath: .spec.labelValue
      name: Value
      type: string
    - description: Number of matching Pods
      jsonPath: .status.entries[*].podName
      name: Pods
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PodSvc is the Schema for the podsvcs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: PodSvcSpec defines the desired state of PodSvc
            properties:
              labelName:
                description: LabelName is the key of the label used to select Pods.
                type: string
              labelValue:
                description: LabelValue is the value of the label used to select Pods.
                type: string
              ports:
                description: |-
                  Ports defines the desired service ports.
                  These are matched against Pod container ports.
                items:
                  description: ServicePort contains information on service's port.
                  properties:
                    appProtocol:
                      description: |-
                        The application protocol for this port.
                        This is used as a hint for implementations to offer richer behavior for protocols that they understand.
                        This field follows standard Kubernetes label syntax.
                        Valid values are either:

                        * Un-prefixed protocol names - reserved for IANA standard service names (as per
                        RFC-6335 and https://www.iana.org/assignments/service-names).

                        * Kubernetes-defined prefixed names:
                          * 'kubernetes.io/h2c' - HTTP/2 prior knowledge over cleartext as described in https://www.rfc-editor.org/rfc/rfc9113.html#name-starting-http-2-with-prior-
                          * 'kubernetes.io/ws'  - WebSocket over cleartext as described in https://www.rfc-editor.org/rfc/rfc6455
                          * 'kubernetes.io/wss' - WebSocket over TLS as described in https://www.rfc-editor.org/rfc/rfc6455

                        * Other protocols should use implementation-defined prefixed names such as
                        mycompany.com/my-custom-protocol.
                      type: string
                    name:
                      description: |-
                        The name of this port within the service. This must be a DNS_LABEL.
                        All ports within a ServiceSpec must have unique names. When considering
                        the endpoints for a Service, this must match the 'name' field in the
                        EndpointPort.
                        Optional if only one ServicePort is defined on this service.
                      type: string
                    nodePort:
                      description: |-
                        The port on each node on which this service is exposed when type is
                        NodePort or LoadBalancer.  Usually assigned by the system. If a value is
                        specified, in-range, and not in use it will be used, otherwise the
                        operation will fail.  If not specified, a port will be allocated if this
                        Service requires one.  If this field is specified when creating a
                        Service which does not need it, creation will fail. This field will be
                        wiped when updating a Service to no longer need it (e.g. changing type
                        from NodePort to ClusterIP).
                        More info: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
                      format: int32
                      type: integer
                    port:
                      description: The port that will be exposed by this service.
                      format: int32
                      type: integer
                    protocol:
                      default: TCP
                      description: |-
                        The IP protocol for this port. Supports "TCP", "UDP", and "SCTP".
                        Default is TCP.
                      type: string
                    targetPort:
                      anyOf:
                      - type: integer
                      - type: string
                      description: |-
                        Number or name of the port to access on the pods targeted by the service.
                        Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
                        If this is a string, it will be looked up as a named port in the
                        target Pod's container ports. If this is not specified, the value
                        of the 'port' field is used (an identity map).
                        This field is ignored for services with clusterIP=None, and should be
                        omitted or set equal to the 'port' field.
                        More info: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
                      x-kubernetes-int-or-string: true
                  required:
                  - port
                  type: object
                minItems: 1
                type: array
            required:
            - labelName
            - labelValue
            - ports
            type: object
          status:
            description: PodSvcStatus defines the observed state of PodSvc
            properties:
              entries:
                description: Entries contains one entry per Pod that matches the selector.
                items:
                  description: PodSvcStatusEntry describes the state of a single Pod
                    managed by this CR.
                  properties:
                    matchedPorts:
                      description: MatchedPorts are the ports that successfully matched
                        Pod container ports.
                      items:
                        description: ServicePort contains information on service's
                          port.
                        properties:
                          appProtocol:
                            description: |-
                              The application protocol for this port.
                              This is used as a hint for implementations to offer richer behavior for protocols that they understand.
                              This field follows standard Kubernetes label syntax.
                              Valid values are either:

                              * Un-prefixed protocol names - reserved for IANA standard service names (as per
                              RFC-6335 and https://www.iana.org/assignments/service-names).

                              * Kubernetes-defined prefixed names:
                                * 'kubernetes.io/h2c' - HTTP/2 prior knowledge over cleartext as described in https://www.rfc-editor.org/rfc/rfc9113.html#name-starting-http-2-with-prior-
                                * 'kubernetes.io/ws'  - WebSocket over cleartext as described in https://www.rfc-editor.org/rfc/rfc6455
                                * 'kubernetes.io/wss' - WebSocket over TLS as described in https://www.rfc-editor.org/rfc/rfc6455

                              * Other protocols should use implementation-defined prefixed names such as
                              mycompany.com/my-custom-protocol.
                            type: string
                          name:
                            description: |-
                              The name of this port within the service. This must be a DNS_LABEL.
                              All ports within a ServiceSpec must have unique names. When considering
                              the endpoints for a Service, this must match the 'name' field in the
                              EndpointPort.
                              Optional if only one ServicePort is defined on this service.
                            type: string
                          nodePort:
                            description: |-
                              The port on each node on which this service is exposed when type is
                              NodePort or LoadBalancer.  Usually assigned by the system. If a value is
                              specified, in-range, and not in use it will be used, otherwise the
                              operation will fail.  If not specified, a port will be allocated if this
                              Service requires one.  If this field is specified when creating a
                              Service which does not need it, creation will fail. This field will be
                              wiped when updating a Service to no longer need it (e.g. changing type
                              from NodePort to ClusterIP).
                              More info: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
                            format: int32
                            type: integer
                          port:
                            description: The port that will be exposed by this service.
                            format: int32
                            type: integer
                          protocol:
                            default: TCP
                            description: |-
                              The IP protocol for this port. Supports "TCP", "UDP", and "SCTP".
                              Default is TCP.
                            type: string
                          targetPort:
                            anyOf:
                            - type: integer
                            - type: string
                            description: |-
                              Number or name of the port to access on the pods targeted by the service.
                              Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
                              If this is a string, it will be looked up as a named port in the
                              target Pod's container ports. If this is not specified, the value
                              of the 'port' field is used (an identity map).
                              This field is ignored for services with clusterIP=None, and should be
                              omitted or set equal to the 'port' field.
                              More info: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
                            x-kubernetes-int-or-string: true
                        required:
                        - port
                        type: object
                      type: array
                    podName:
                      description: PodName is the name of the Pod.
                      type: string
                    serviceName:
                      description: ServiceName is the name of the Service created
                        for this Pod.
                      type: string
                    unmatchedPorts:
                      description: UnmatchedPorts are CR ports that did not match
                        any Pod container port.
                      items:
                        description: UnmatchedPortStatus describes a port from the
                          CR that failed to match.
                        properties:
                          name:
                            type: string
                          port:
                            format: int32
                            type: integer
                          protocol:
                            type: string
                          reason:
                            type: string
                        required:
                        - port
                        type: object
                      type: array
                  required:
                  - podName
                  - serviceName
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
